---
- hosts: vm
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
        
    - name: Install Python3
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Airflow using pip
      pip:
        name: apache-airflow
        state: present
        executable: pip3

    - name: Install Airflow Docker provider using pip
      pip:
        name: apache-airflow-providers-docker
        state: present
        executable: pip3

    - name: Set Airflow executor
      ansible.builtin.lineinfile:
        path: /home/vagrant/airflow/airflow.cfg
        regexp: '^load_examples ='
        line: 'load_examples = False'
        mode: '0644'

    - name: Install Docker dependencies
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        update_cache: yes

    - name: Add Docker's official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Verify that Docker's official GPG key is present
      command: apt-key fingerprint 0EBFCD88
      register: result
      failed_when: "'Docker' not in result.stdout"

    - name: Get Ubuntu codename
      shell: lsb_release -cs
      register: ubuntu_codename

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
        state: present
        update_cache: true

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes