---
- hosts: vm
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'
        
    - name: Install Python3
      apt:
        name: python3
        state: present

    - name: Install pip
      apt:
        name: python3-pip
        state: present

    - name: Install Airflow using pip
      pip:
        name: apache-airflow
        state: present
        executable: pip3

    - name: Set Airflow executor
      ansible.builtin.lineinfile:
        path: /home/vagrant/airflow/airflow.cfg
        regexp: '^load_examples ='
        line: 'load_examples = False'
        mode: '0644'
